spring:
  application:
    name: crypto-wallet-manager

  datasource:
    url: jdbc:postgresql://localhost:5432/crypto_wallet_manager
    username: crypto_wallet_manager_app
    password: secret

  sql:
    init:
      mode: always

integration:
  coin-cap:
    api-key: ${COIN_CAP_API_KEY} # Set $COIN_CAP_API_KEY env variable with your CoinCap api token or define directly here
    base-url: https://rest.coincap.io/v3

job:
  update_price_frequency: 10S
